### ISSUE TITLE
chooseColumnSpec control is visualized twice (no such issue in DSW 1.x)

### ISSUE THREAD

**Issue by dmitry-zasypkin** [intersystems-community/DeepSeeWeb#130]
Extract from dashboard:
```
    <control name="" action="chooseColumnSpec" target="" targetProperty="HU2mapDSW2.termlist" location="widget" type="auto" controlClass="" label="Measure to colorize the map" title="" value="" text="" readOnly="false" valueList="" displayList="" activeWhen="">
      <valueRequired>false</valueRequired>
    </control>
```
### Latest release of DSW 2 shows both a label+dropdown (expeted) and a button with the same label (unexpected!):
![image](https://user-images.githubusercontent.com/13035460/68427794-e3c3e600-01bb-11ea-9cb3-3283bed002cf.png)

### DSW 1.4.76 visualizes the same dashboard on the same IRIS instance correctly:
![image](https://user-images.githubusercontent.com/13035460/68428499-61d4bc80-01bd-11ea-8871-2078b127e5db.png)

**Comment by evshvarov** [comment]
Fixed with the 1.37 release

**Comment by dmitry-zasypkin** [comment]
No, not fixed. I've just installed 2.1.38, and the extra button is still there.

**Comment by evshvarov** [comment]
BTW, ZPM now works on IRIS for Health
