### ISSUE TITLE
Default range filters with now are not visible

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/DeepSeeWeb#403]
E.g. if the month filter is like this:
[NOW-6]:&[NOW-1] 
meaning last 5 months
it is not visible in filters and in widgets in the implied filter indicator.

**Comment by Lena-Ev** [comment]
fixed try to update to 3.2.10

**Comment by evshvarov** [comment]
Still doesn't work if the filter is a range:
<img width="298" alt="Screenshot 2023-09-21 at 6 32 33 PM" src="https://github.com/intersystems-community/DeepSeeWeb/assets/2781759/8f3a99b9-8a25-44fb-bec0-94a47ade8d66">

**Comment by Lena-Ev** [comment]
example please
without calendar 
months

**Comment by Frisle** [comment]
Here is the example
https://pie-chart-bug.demo.community.intersystems.com/dsw/index.html#/USER/Two%20Subject%20Areas%20Together.dashboard

And the filter value syntaxis 
![image](https://github.com/intersystems-community/DeepSeeWeb/assets/47441164/f69da8a7-af9b-435a-848f-8493bb115a5e)

The data is filtered fine, but the filter value itself is not displayed.

**Comment by gnibeda** [comment]
fixed in 3.2.17

**Comment by Lena-Ev** [comment]
@evshvarov could you please see it on your data and close issue if all is good

**Comment by Frisle** [comment]
Filters still show whole range of dates. On top of that data does not filter according to filter values

![chrome_70XVKepSNZ](https://github.com/intersystems-community/DeepSeeWeb/assets/47441164/afb75bec-9ceb-4c5e-b926-3483f608eb88)
